/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  X402USDCReceipt,
  X402USDCReceiptInterface,
} from "../../contracts/X402USDCReceipt";

const _abi = [
  {
    inputs: [],
    name: "AlreadyPaid",
    type: "error",
  },
  {
    inputs: [],
    name: "AmountZero",
    type: "error",
  },
  {
    inputs: [],
    name: "Expired",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidRecipient",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidToken",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "resourceHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
    ],
    name: "X402Paid",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
    ],
    name: "isPaid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "resourceHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "receipts",
    outputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "resourceHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "paidAt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610016576103b2908161001c8239f35b600080fdfe6080604081815260048036101561001557600080fd5b600092833560e01c908163b0259c2e146100f157508063ef6cf04d146100725763feef66401461004457600080fd5b3461006e57602036600319011261006e578160209360069235815280855220015415159051908152f35b8280fd5b503461006e57602036600319011261006e57816101009382358152806020522080549260018201549260018060a01b03908160028501541691806003860154169185015416916005850154936007600687015496015496815198895260208901528701526060860152608085015260a084015260c083015260e0820152f35b9050346103785760c0366003190112610378576001600160a01b03604435818116946024359480359490928790036103745760643590848216809203610370576084359360a43595878b526020928b84526006868d200154610362575086151580610359575b61034a57891561033b57831561032c57851561031d5784516323b872dd60e01b81523383820152602481018b90526044810187905283816064818f895af18015610313576102ae575b50845191610100830183811067ffffffffffffffff82111761029b578786858f958f958f968f978f988a8f919b8e60079d899c8552808a52818a0195865260e060c0868c019b338d5260608101998a52608081019d8e5260a081019e8f52019d8e429052019d8e52825252209a518b555160018b01558260028b01945116936bffffffffffffffffffffffff60a01b94858254161790558260038b019151168482541617905588019251169082541617905551600585015551600684015551910155825197885287015285015260608401527f0f11fa175548e06b81f4533ce4c1266480296666de4fe798c9bc1b634c72a6fb60803394a480f35b634e487b7160e01b8d526041825260248dfd5b833d851161030c575b601f8101601f1916820167ffffffffffffffff8111838210176102f957859183918952810103126102f55751801515036102f157386101a0565b8a80fd5b8b80fd5b634e487b7160e01b8e526041855260248efd5b503d6102b7565b86513d8e823e3d90fd5b5083516365e52d5160e11b8152fd5b50835163c1ab6dc160e01b8152fd5b508351634e46966960e11b8152fd5b508351630407b05b60e31b8152fd5b50864211610157565b630d70a0e360e41b81529050fd5b8880fd5b8780fd5b8380fdfea264697066735822122053eedfa2436ed8b9c9611c6d60e7491f5fe491afeaf946bc9442dd51471c914464736f6c63430008140033";

type X402USDCReceiptConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: X402USDCReceiptConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class X402USDCReceipt__factory extends ContractFactory {
  constructor(...args: X402USDCReceiptConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      X402USDCReceipt & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): X402USDCReceipt__factory {
    return super.connect(runner) as X402USDCReceipt__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): X402USDCReceiptInterface {
    return new Interface(_abi) as X402USDCReceiptInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): X402USDCReceipt {
    return new Contract(address, _abi, runner) as unknown as X402USDCReceipt;
  }
}
